blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, HomeListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    VersionCreateView, VersionUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product_detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('update_product/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('create_version/', VersionCreateView.as_view(), name='create_version'),
    path('update_version/<int:pk>/', VersionUpdateView.as_view(), name='update_version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls'), name='catalog'),
                  path('', include('blog.urls'), name='blog'),
                  path('users/', include('users.urls'), name='users')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/models.py
from django.conf import settings
from django.db import models

from Category.models import Category
from users.models import NULLABLE


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    # name = models.CharField(max_length=100, verbose_name='Наименование', unique=True) unique проверяет уникольное значение
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images/', null=True, verbose_name='Изображение (превью)')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за штуку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.SET_NULL,
                              **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Наименование продукта')
    version_number = models.CharField(max_length=20, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Наименование версии')
    is_current = models.BooleanField(default=False, verbose_name='Признак версии')

    def __str__(self):
        return f"{self.product.name} - {self.version_name} - {self.version_number}"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/models.py
from django.db import models

# Create your models here.

catalog/forms.py
from django import forms

from Product.models import Product, Version

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('owner',)

        # fields = ('name', 'description', 'image', 'category', 'price',)
        fields = ['name', 'description', 'image', 'category', 'price', 'is_published']
        # fields = '__all__'
        # exclude = ['price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        # for field_name, field in self.fields.items():
        #     field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        name = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError("Название содержит запрещенные слова")
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError("Описание содержит запрещенные слова")
        return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version

        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-control'


class ModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['description', 'category', 'is_published']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

Product/views.py
from django.shortcuts import render

# Create your views here.

catalog/views.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from Product.models import Product, Version
from catalog.forms import ProductForm, VersionForm, ModeratorForm
from catalog.services import get_cached_category_for_product


# Create your views here.

class HomeListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'SkyStore'
        products = Product.objects.all()
        active_versions = {}
        for product in products:
            active_versions[product] = Version.objects.filter(product=product, is_current=True).first()
            context['active_versions'] = active_versions
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


# def home(request):
#     products_list = Product.objects.all()
#     context = {
#         'object_list': products_list,
#         'title': 'SkyStore'
#     }
#     return render(request, 'catalog/home.html', context)

@login_required()
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}, {phone}, {message}')

    context = {
        'title': 'Контакты'
    }

    return render(request, 'catalog/contacts.html', context)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'SkyStore'
        return context


# def product_detail(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(id=pk),
#         'title': f'SkyStore {product_item.name}'
#     }
#     return render(request, 'catalog/product_detail.html', context)

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'SkyStore'

        # Используем кешированную функцию
        category_list = get_cached_category_for_product()

        context['category_list'] = category_list

        products = Product.objects.all()
        active_versions = {}

        for product in products:
            active_versions[product] = Version.objects.filter(product=product, is_current=True).first()

        context['active_versions'] = active_versions
        return context


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:home')

    def get_form_class(self):
        if self.request.user.is_staff and self.request.user.groups.filter(
                name='moderator').exists():
            return ModeratorForm
        return ProductForm

    def test_func(self):
        _user = self.request.user
        _instance: Product = self.get_object()
        custom_perms: tuple = (
            'catalog.set_is_published',
            'catalog.set_category',
            'catalog.set_product_description',
        )
        if _user.is_superuser or _user == _instance.owner:
            return True
        elif _user.groups.filter(name='moderator') or _user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:home')

    def get_form_class(self):
        if self.request.user.is_staff and self.request.user.groups.filter(
                name='moderator').exists():
            return ModeratorForm
        return ProductForm

    def test_func(self):
        _user = self.request.user
        _instance: Product = self.get_object()
        custom_perms: tuple = (
            'catalog.set_is_published',
            'catalog.set_category',
            'catalog.set_product_description',
        )
        if _user.is_superuser or _user == _instance.owner:
            return True
        elif _user.groups.filter(name='moderator') or _user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version
    template_name = 'catalog/version_form.html'
    form_class = VersionForm
    success_url = reverse_lazy('catalog:home')


class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = Version
    template_name = 'catalog/version_form.html'
    form_class = VersionForm
    permission_required = 'product.change_version_product'
    success_url = reverse_lazy('catalog:home')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     ParentFormset = inlineformset_factory()
    #
    #     return context
    #
    # def form_valid(self, form):
    #     return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_mainmenu.html' %}

{% block content%}
{% endblock %}

<div class="container">
    <div class="row text-center">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                {{ title }}
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <nav class="ms-5">
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_version' %}">Добавить версию
                    продукта</a>
            {% else %}
                <p class="lead">Для работы с продуктами войдите в аккаунт или зарегистрируйтесь.</p>
            {% endif %}
        </nav>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
            продать</p>
    </div>

    <div class="container">
        <div class="row text-center">
            {% for object, active_version in active_versions.items %}
                {#                {% for version in object.version_set.all %}#}
                {#                    {% if version.is_active %}#}
                {#                        {{ version }}#}
                {#                    {% endif %}#}
                {#                {% endfor %}#}
                {#                Исправить на код в комментарии Лучше всё же получать версию непосредственно из продукта.#}
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object | title }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">$ {{ object.price }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ object.description | slice:":100" }}</li>
                                {#                        <img src="{% static object.image %}" class="img-fluid" alt="{{ object | title }}">#}
                                <img src="{{ object.image | mediapath }}" class="img-fluid" alt="{{ object | title }}">
                                <li>
                                    {% if active_version %}
                                        Version: {{ active_version.version_name }}
                                        <li>
                                            Version number: {{ active_version.version_number }}
                                        </li>
                                    {% else %}
                                        No active version
                                    {% endif %}
                                <li>Пользователь: {{ object.owner | default:'Без пользователя' }}</li>
                                </ul>
                            {% if user.is_authenticated %}
                                <a href="{% url 'catalog:product_detail' object.pk %}" type="button"
                                   class="btn btn-lg btn-block btn-outline-primary">View</a>
                                <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                                   class="btn btn-lg btn-block btn-outline-primary">Edit</a>
                                <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                                   class="btn btn-lg btn-block btn-outline-danger">Delete</a>
                            {% else %}
                                <p class="lead">Для работы с продуктами войдите в аккаунт или зарегистрируйтесь.</p>
                            {% endif %}
                            {#                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_version' object.pk %}">Добавить#}
                            {#                                версию продукта</a>#}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div class="card-title">
                            Удаление продукта
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                Удалить продукт {{ object }}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                <a href='{% url 'catalog:home' %}' class="btn btn-success">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <body>
    <div class="container">
        <div class="row text-center">
            {#            {% for object in object_list %}#}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object | title }}</h4>
                    </div>
                    <div class="card-body">
                        <h1>{{ object.name }}</h1>
                        <p>Description: {{ object.description }}</p>
                        <p>Price: {{ object.price }}</p>
                        {#                            <img src="{% static object.image %}" class="img-fluid" alt="{{ product | title }}">#}
                        <img src="{{ object.image | mediapath }}" class="img-fluid" alt="{{ object | title }}">
                        <p></p>
                        <p>Category: {{ object.category }}</p>
                        <p>created_at: {{ object.created_at }}</p>
                        <p>updated_at: {{ object.updated_at }}</p>
                        <p>Пользователь: {{ object.owner|default:'Без пользователя' }}</p>
                    </div>
                </div>
            </div>
            {#            {% endfor %}#}
        </div>
    </div>
    </body>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div class="card-title">
                            Добавление продукта
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
{#                                {{ form.as_p }}#}
                                {% crispy form %}
{#                                <button type="submit" class="btn btn-success">Сохранить</button>#}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <div class="card-title">
                            Добавление версии продукта
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
{#                                {{ form.as_p }}#}
{#                                <button type="submit" class="btn btn-success">Сохранить</button>#}
                                {% crispy form %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}